[package]
name = "mountain-maker"
version = "0.1.0"
edition = "2024"

[dependencies]
mesh-tools = "0.4.0"
rand = "0.8"
glam = "0.24"
bytemuck = "1.14"
anyhow = "1.0"
clap = { version = "4.4.11", features = ["derive"] }
noise = "0.9"
image = "0.24"

[dev-dependencies]
gltf = "1.4"
